FROM golang:1.22.5-alpine

WORKDIR /app

# Install required packages 
RUN apk add --no-cache \
    g++ \
    gcc \
    python3 \
    nodejs \
    musl-dev \
    curl \
    bash

# Copy warmup files
COPY warmup.go .

# Initialize Go module and warm up
RUN go mod init warmup && \
    go run warmup.go

# Ensure the app can run (add temp directory for any necessary writes)
RUN mkdir -p /app/temp && chmod 777 /app/temp

# Command to keep the container running
CMD ["tail", "-f", "/dev/null"]